### ISSUE TITLE
Timestamps in backup filenames

### ISSUE THREAD

**Issue by silic0nalph4** [jan-di/docker-database-backup#13]
Hi, thanks for the awesome tool! I've added it to a Docker Compose [cluster](https://github.com/silic0nalph4/nova-secura-10) I'm running - it's great to have automatic backups 😀

I was wondering what you thought of the following feature request:

> Add a config option that appends a timestamp to the backup filename. This would allow multiple backups to be written out from a service and remove the need for another tool to rename the files before archiving them.

I think it makes most sense for the config option to be at the database level rather than global, so it could be set for some databases and not others.

e.g.
```
# Minimal Docker Compose usage example
version: '3.8'

services:
  db-backup: # backup service
    image: ghcr.io/jan-di/database-backup
    environment:
      - TZ=Europe/Berlin
      - SCHEDULE=600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  database1: # well known database image
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret-password
    labels:
      - jan-di.database-backup.enable=true
      - jan-di.database-backup.dump_timestamp=true <-- This bit is new.
```

Output;
- `/dump/database1_2021-10-30T14:35:40+00:00.sql` (ISO 8601)

Would this be something that you'd be interested in adding to this tool? If so I'm happy to have a hack at implementing it (but don't want to step on your toes!)
